name: Changelog
description: Update changelog
inputs:
  token:
    description: GitHub access token for github_changelog_generator
    required: false
    default: ${{ github.token }}
  future-release:
    description: The future release version for github_changelog_generator
    required: false
    default: ""
  since-tag:
    description: Generate changelog since the specified tag.
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3
    - run: gem install github_changelog_generator
      shell: bash
    - name: Update CHANGELOG.md
      shell: bash -euxo pipefail {0}
      run: |
        suffix=()
        if [[ -n '${{ inputs.future-release }}' ]]; then
          suffix+=(--future-release '${{ inputs.future-release }}')
        fi

        if [[ -n '${{ inputs.since-tag }}' ]]; then
          suffix+=(--since-tag '${{ inputs.since-tag }}')
        fi

        github_changelog_generator \
          --user "${GITHUB_REPOSITORY%/*}" \
          --project "${GITHUB_REPOSITORY#*/}" \
          --exclude-labels chore,no-changelog,duplicate,question,invalid,wontfix \
          --include-tags-regex 'v\d+\.\d+\.\d+' \
          "${suffix[@]}"
      env:
        CHANGELOG_GITHUB_TOKEN: ${{ inputs.token }}
